canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "blue"; 
ctx.beginPath(); 
ctx.strokeStyle = color; 
ctx.lineWidth = 2; 
ctx.arc(200, 200, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown); 
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "red"; 
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "black"; 
ctx.beginPath(); 
ctx.strokeStyle = color; 
ctx.lineWidth = 2; 
ctx.arc(160, 200, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown); 
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "purple"; 
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "pink"; 
ctx.beginPath(); 
ctx.strokeStyle = color; 
ctx.lineWidth = 2; 
ctx.arc(120, 200, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown); 
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "yellow"; 
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "orange"; 
ctx.beginPath(); 
ctx.strokeStyle = color; 
ctx.lineWidth = 2; 
ctx.arc(80, 200, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown); 
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "red";
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "red"; 
ctx.beginPath(); 
ctx.strokeStyle = color; 
ctx.lineWidth = 2; 
ctx.arc(40, 200, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown); 
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "red";  
ctx.beginPath(); 
ctx.strokeStyle = color; 
ctx.lineWidth = 2; 
ctx.arc(240, 200, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown);
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "red"; 
ctx.arc(40, 200, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown); 
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "red";  
ctx.beginPath(); 
ctx.strokeStyle = color; 
ctx.lineWidth = 2; 
ctx.arc(0, 200, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown);
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "red"; 
ctx.beginPath(); 
ctx.strokeStyle = color; 
ctx.lineWidth = 2; 
ctx.arc(270, 200, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown);
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "red"; 
ctx.beginPath(); 
ctx.strokeStyle = color; 
ctx.lineWidth = 2; 
ctx.arc(200, 250, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown);
canvas = document.getElementById("myCanvas"); 
ctx= canvas.getContext("2d"); 
color = "red"; 
ctx.beginPath(); 
ctx.strokeStyle = color; 
ctx.lineWidth = 2; 
ctx.arc(270, 240, 40 ,0 , 2*Math.PI); 
ctx.stroke();
canvas.addEventListener("mousedown", my_mousedown);





function my_mousedown(e) { 
    mouse_x = e.clientX - canvas.offsetLeft; 
    mouse_y = e.clientY - canvas.offsetTop; 
console.log("X = " + mouse_x + " ,Y = " + mouse_y); 
circle(mouse_x , mouse_y); 
}
function circle(mouse_x , mouse_y) { ctx.beginPath(); ctx.strokeStyle = color; ctx.lineWidth = 2; 
ctx.arc(mouse_x, mouse_y, 40 ,0 , 2*Math.PI); ctx.stroke(); 
}
